---

language: python
python: "2.7"
sudo: "required"
dist: "xenial"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible==2.8

script:
  - sudo lsb_release -a
  - ansible --version
  - ansible-playbook -i test/inventory test/test.yml --syntax-check
  - ansible-playbook -i test/inventory test/test.yml --connection=local -vvv
  - snap services amazon-ssm-agent
